### ISSUE TITLE
Web site example

### ISSUE THREAD

**Issue by danenglish2** [alexanderkozlenko/aspnetcore-request-decompression#1]
Hi Alexander.  I see this being a very useful package.  I can't believe it isn't built-in.  I am new to ASP.NET core and couldn't get it working with my web site.  I tried the below code, but it didn't decompress (gets a 404 error).  Am I missing something?  I am trying to receive gzipped json content.

```cs
public void ConfigureServices(IServiceCollection services)
{
            var rd_options = new RequestDecompressionOptions();
            rd_options.UseDefaults();

            services.AddRequestDecompression(rd_options); // support gzip requests

            services.AddMvc();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
            app.UseStaticFiles();

            app.UseRequestDecompression();  // support gzip requests

            app.UseMvcWithDefaultRoute();
}


```
Sorry for the newbie question.  Thank you.

**Comment by danenglish2** [comment]
Actually this is working :)  This would be a nice example for your readme.

**Comment by alexanderkozlenko** [comment]
@danenglish2, thank you for the provided example! I will update the README file accordingly.
