### ISSUE TITLE
Version 1.9.0 Has Dependency on .Net Core 5

### ISSUE THREAD

**Issue by stricq** [alexanderkozlenko/aspnetcore-request-decompression#150]
### Summary

Attempting to upgrade from v1.8.0 to v1.9.0 for .Net Core 3.1 projects fails as v1.9.0 has a dependency on .Net Core 5.0.

If this was intentional, the version should have been bumped to 2.0.0 and the NuGet Description should be updated as well.

### Artifacts

```
U1202: Package Anemonis.AspNetCore.RequestDecompression 1.9.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Anemonis.AspNetCore.RequestDecompression 1.9.0 supports: net5.0 (.NETCoreApp,Version=v5.0)
Package restore failed. Rolling back package changes for '....'.
```

### Environment

.Net Core 3.1

| | |
| --- | --- |
| Product | v.1.9.0 |
| Runtime | .Net Core 3.1 |
| OS | NA |
| Locale | NA |
| Time Zone | NA |

**Comment by alexanderkozlenko** [comment]
Could you please try updating to the 1.10.0 version of the package?
