### ISSUE TITLE
ASP.Net Core 3 does not seem to be decompressing gzip

### ISSUE THREAD

**Issue by mts57017** [alexanderkozlenko/aspnetcore-request-decompression#66]
Hi there!

i recently upgraded to net core 3 and when i attempt to send gzip via postman, and i debug, i still the following....

\u001f�\b\b���]\0\u0003DataLake_RawZone_20191127_20191127123054.1.txt\0�Z[n�V\f��b&$/y\u001f�Eӯ�@�v\u0003E2\u0001\u0002\u0018H\u00108\u0005�!/�++%]I3\u0014/�\t��Ih�\"\u000f\u000f\u000f)\u007f�����_�/\u007f|�r������\u007f���/\u007f?\u007f�q���g��㏯������~���������O��\u000fק����\u0010s��\u0017*�\u0011�\u0013`{}��W\u0006.��\u0005__��~{zz�r�-y�\tP}�\a�Kk�\u0017�5�V<k�$�3cb7����a�,X�8\b$-qХ\u001b�)eqÐc\u0018��\u0001j�\u001dK���1\u0011fqcF��\u0005n\u001c\u0013\u0011�|.� ��\r\"\u0001���P\"q����\u0018R*\u0005�D\u0010�bK���X*�\u0005!j=ŲZ�a��0��\b����0\u0015\u0019D\u0001,K�e�E\u0012*�ǜ�x\u001e�\u0002r��s�\u0013���L�Ø�!�*�/65H�1��\u0013\u0013Ek2}7�\u0016�g\u000en��\"���\u0016\f�\u0018`\u0010E\u0003�Os\u0014>\u0005\u0014^�\t�\\��0\"�C9ߪͶj踞o?hg�O��@���O�\u0002t�ᰡ�0�v���4��_���-r]0��O�0\fӨL�d��H�۩\\�x6IF�V�֛\u001f|�\0���\u0014Pi\u001a\u0001$���q��\u001b�\u001d3F�\u001d\u0015٢�\r��V;�����V�\u001f\u000e�\u0015����\u0015]d \u0016������ ^�o�k�\u0005�B\u00153,Np��8�_\u007fH2t���w�f\u001b0}��\u0016\u07b4�ia)�;\u001fG\u0011۬E��4�=�ȼ��G�.�M����R�,�༅\\�UW�!6Ko�-�\aP��\bF\u0013�a����\a[[�ǗB[���F\f3���\u0005�Y����\a �d��!%����\u0006�%Nk=�M�\u0012�D~�\n�\u0001\u0019���X�!�Jj�a1\u0011�Å+\u0001��\t�4��w\u0019Ʌ�v<\r�\u0016�t����a�S\u001fC\0��-RV�\u001b\u0004aX3�0?���Y�\u001ak\u0005�K����\u0012K\u0016���6�X*Z \u0017�G�\u0017�5�\bm\u000f�.�5\tF����.�����#��\u0001��Ht_`�:�\u0010��\u0010x6�pʣ?\u001c�v\f��o��J��*\u00021\u001b�˕\u0013���43>P�jŁ���?�v2�ӂ~�~+�gv[�XLE\u0012�2�)xɅ�]\u0011�V��Ȫ�1\r��[B�U\u0018\u0017\u001c'9Sj|�A�44��g7\u0005T\\��p��;��x��&>�69\u007f��6iTf{\b\t�c��\u001d�SN�u�z\u0011�\u000eS�M�'�d\"�\u0019���*��������M\n�뿖�BH;wR\u001a�4絙:6;�y �\u05fd\t���<�ؼ���i�[&�z�}eJ:�r7W�P����QGrY�z�c\u0015K���%�1!\n\u0019�0bx(�\a��l�\u0010��\u001d�Q\fv�G��[#[�\u0002:��`+L�t�(>át\b�����O�Z��\a\"��l�i@��5dQd+\u000fD\bJ\u0006�ѝ5\u001b��R�@C�\u0013uj�zI�^��}��\u001c���\u001eo����̈w��l�R\u0018��K(hj\u0006{l^z#�ƝH:�\\��o\u0005�\u0010�i\u000e���Eh/GdkS����6�V�e,HE{ �ͨ��\u0010�*/�Դ�g:�4��~�Ɩ�F�qc�_�܅̉�\u0018t\fٷ\u0005�>�k��wi��q/\u001dV����m��\0����n���A�:kb���\u00045�v\nqٖ$�pd�B\u0005K�o&�s��2\u001e�l�z\u0005\v��B�αr�\u001f�&Z\u0010�Y�\n�\u00112,�\u0004�[/u;�\"����\u0018:���3�ѵ���ס��c�(�\u000e��џ�\nN| k�\u0001[\u0013�\fb?�\a�\u0004�7\a\v5uŴ�9�<��zhk4^tj:\u001cM�Z�y�4z@\r6;�\u0002�z\u0004;�q\u0017�`j<�śRQ%&o��!���\u000e���<���T7����\u0002�������\u0006\u0012�����\u001af�\u0003\u001d_�\u0004~��\u0016%���2��?���g���L�W�پ�\u001e\u001fy֛-���ǣ\u001f��?-���5��ܺ�Z\u0012#\0\0

it appears it is not being decompressed, right?

thanks for any help you can provide here!

**Comment by alexanderkozlenko** [comment]
Hi @mts57017, thank you for reporting the issue.

Could you please provide details required for investigation: product, runtime, and OS versions? How the middleware is activated and configured, what are the log messages with debug log level, what are request headers? A sample of a request and a response, source code for reproducing will help as well. Could you please also attach sample binary data as a file instead of text representation?

Thank you in advance!
