### ISSUE TITLE
I am note able to use request decompression feature in my ASP.NET Web API

### ISSUE THREAD

**Issue by MuraliKrx** [alexanderkozlenko/aspnetcore-request-decompression#81]
I am using this package to decompress a gzipped post request, received at the web server. But at the web server application end, still the data seems to be in the compressed format. I have attached my startup.cs file. Please look into it and provide me a suggestion on how to use it. 

Also how do i test its working?

`public void ConfigureServices(IServiceCollection services)
        {
            services.AddRequestDecompression(o =>
            {
                o.Providers.Add<DeflateDecompressionProvider>();
                o.Providers.Add<GzipDecompressionProvider>();
                o.Providers.Add<BrotliDecompressionProvider>();
            });
            services.AddControllers().AddJsonOptions( options =>
            {
                options.JsonSerializerOptions.IgnoreNullValues = true;
            });
            services.AddControllersWithViews(options=>
                {
                    options.Filters.Add(typeof(OMFExceptionFilter));
                }
             );
            services.AddMvc(option => option.EnableEndpointRouting = false);
        }`

        `// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseRequestDecompression();

            app.UseRouting();
            app.UseAuthentication();

            app.UseMvc();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            DBData dbData = new DBData();
        }`

**Comment by alexanderkozlenko** [comment]
> I am using this package to decompress a gzipped post request, received at the web server. But at the web server application end, still the data seems to be in the compressed format. I have attached my startup.cs file. Please look into it and provide me a suggestion on how to use it. 
> 
> Also how do i test its working?
> 
> ```cs
> public void ConfigureServices(IServiceCollection services)
> {
>     services.AddRequestDecompression(o =>
>     {
>         o.Providers.Add<DeflateDecompressionProvider>();
>         o.Providers.Add<GzipDecompressionProvider>();
>         o.Providers.Add<BrotliDecompressionProvider>();
>     });
>     services.AddControllers().AddJsonOptions( options =>
>     {
>         options.JsonSerializerOptions.IgnoreNullValues = true;
>     });
>     services.AddControllersWithViews(options=>
>         {
>             options.Filters.Add(typeof(OMFExceptionFilter));
>         }
>         );
>     services.AddMvc(option => option.EnableEndpointRouting = false);
> }
> ```
> 
> ```cs
> // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
> public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
> {
> 
>     if (env.IsDevelopment())
>     {
>         app.UseDeveloperExceptionPage();
>     }
>     else
>     {
>         app.UseExceptionHandler("/Home/Error");
>         // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
>         app.UseHsts();
>     }
> 
> 
>     app.UseHttpsRedirection();
>     app.UseDefaultFiles();
>     app.UseStaticFiles();
> 
>     app.UseRequestDecompression();
> 
>     app.UseRouting();
>     app.UseAuthentication();
> 
>     app.UseMvc();
>     app.UseAuthorization();
> 
>     app.UseEndpoints(endpoints =>
>     {
>         endpoints.MapControllers();
>     });
> 
>     DBData dbData = new DBData();
> }
> ```

@MuraliKrx, could you please add information required to investigate the case such as runtime type and version, library version (if it's possible, it would be helpful also to specify all the information suggested by the bug report template). Thanks!

**Comment by MuraliKrx** [comment]
I am using Visual Studio Community 2019 as the IDE.
The .NET framework version is 4.7.03190
Anemonis.AspNetCore.RequestDecompression v1.6.0

**Comment by alexanderkozlenko** [comment]
Version 1.6.0 of the library supports only .NET Core as a target runtime. Thus, I suppose, your project targets .NET Core as well. Is it correct? If so, could you please specify the exact version (3.0 or 3.1) and the exact version of .NET Core runtime your run the project on?

**Comment by MuraliKrx** [comment]
Yes, correct. It is .NET core 3.1.1

**Comment by MuraliKrx** [comment]
@alexanderkozlenko Any leads on this?

**Comment by alexanderkozlenko** [comment]
@MuraliKrx, I have created a solution with a working example of decompressing middleware which works only when `UseRequestDecompression` is invoked in `Startup` class (attached). Could you please provide dumps of request and response (e.g.m created with Fiddler) where HTTP message headers are visible and exact exception thrown. A full example (a solution) of the issue is much appreciated.

[WebApplication1.zip](https://github.com/alexanderkozlenko/aspnetcore-request-decompression/files/4270919/WebApplication1.zip)

**Comment by MuraliKrx** [comment]
Thanks @alexanderkozlenko, With the sample file, I was able to find out the implementation of the package. I suggest providing the complete Startup.cs in the readme of the package.
